baseurl = "https://hugo-demo-dylancunningham.netlify.app"
DefaultContentLanguage = "en"
title = "Celestial Spec (hugo demo)"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  
  description = "Unofficial personal Hugo demo. Not affiliated with the Eclipse Foundation."
  seo_title_suffix = ""
  keywords = ["eclipse", "project", "plug-ins", "plugins", "java", "ide", "swt", "refactoring", "free java ide", "tools", "platform", "open source", "development environment", "development", "ide"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "https://www.eclipse.org/home/search/"
  header_wrapper_class = "header_wrapper_class"
  call_for_action_text = "Download"
  call_for_action_url = "//eclipse.org/downloads/"
  call_for_action_icon = "fa-download"
  hide_ad = false
  featured_content_publish_target = "eclipse_org"
  sidebar_layout = "default"
# js = ""
# styles = ""
# logo = ""
# favicon = ""
# share_img = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
# show_events = true
# table_classes = "table table-bordered"
# hide_cfa_same_page = true
# show_collapsible_menu = true

[taxonomies]
  tag = "tags"

[Params.author]
  name = "Eclipse Foundation"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "eclipsefdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.sidebar]]
  name = "Documentation"
  url = "/home"
  weight = 1
  identifier = "home"

[[menu.sidebar]]
  parent ="home"
  name = "Solstice Assets"
  url = "https://webdev.eclipse.org/docs/solstice/"
  weight = 2

[[menu.sidebar]]
  parent ="home"
  name = "Solstice Components"
  url = "https://webdev.eclipse.org/docs/components/"
  weight = 3

[[menu.sidebar]]
  parent = "home"
  name = "Hugo"
  weight = 1
  identifier = "hugo"

[[menu.sidebar]]
  parent ="hugo"
  name = "Hugo Framework"
  url = "https://gohugo.io/documentation/"
  weight = 1

[[menu.sidebar]]
  parent ="hugo"
  name = "Hugo Solstice Theme"
  url = "https://webdev.eclipse.org/docs/hugo/"
  weight = 2

# Uncomment [[menu.main]] to hide the default EF menu
# or to define your own menu links.

# [[menu.main]]
